const wordPairs = [
  { word: "Firetruck", hint: "Response" },
  { word: "Casino", hint: "Risk" },
  { word: "Tattoo", hint: "Expression" },
  { word: "Motorcycle", hint: "Transportation" },
  { word: "Prison", hint: "Confinement" },
  { word: "Volcano", hint: "Nature" },
  { word: "Astronaut", hint: "Exploration" },
  { word: "Submarine", hint: "Stealth" },
  { word: "Dragon", hint: "Legend" },
  { word: "Cemetery", hint: "Death" },
  { word: "Helicopter", hint: "Movement" },
  { word: "Shotgun", hint: "Force" },
  { word: "Whiskey", hint: "Consumption" },
  { word: "Skyscraper", hint: "Structure" },
  { word: "Tornado", hint: "Disaster" },
  { word: "Detective", hint: "Mystery" },
  { word: "Mansion", hint: "Wealth" },
  { word: "Pirate", hint: "Adventure" },
  { word: "Bank", hint: "Finance" },
  { word: "Diamond", hint: "Value" },
  { word: "Robot", hint: "Technology" },
  { word: "Ambulance", hint: "Response" },
  { word: "Nightclub", hint: "Nightlife" },
  { word: "Sword", hint: "Combat" },
  { word: "Hospital", hint: "Care" },
  { word: "Airplane", hint: "Transportation" },
  { word: "Train", hint: "Travel" },
  { word: "Shark", hint: "Predator" },
  { word: "Lighthouse", hint: "Guidance" },
  { word: "Castle", hint: "Power" },
  { word: "Zombie", hint: "Undead" },
  { word: "Vampire", hint: "Undead" },
  { word: "Police", hint: "Authority" },
  { word: "Courtroom", hint: "Justice" },
  { word: "Bullet", hint: "Impact" },
  { word: "Rocket", hint: "Launch" },
  { word: "Satellite", hint: "Technology" },
  { word: "Backpack", hint: "Carrying" },
  { word: "Cigar", hint: "Habit" },
  { word: "Gold", hint: "Value" },
  { word: "Crown", hint: "Status" },
  { word: "Throne", hint: "Power" },
  { word: "Jungle", hint: "Wildness" },
  { word: "Desert", hint: "Isolation" },
  { word: "Blizzard", hint: "Cold" },
  { word: "Hurricane", hint: "Destruction" },
  { word: "Compass", hint: "Navigation" },
  { word: "Treasure", hint: "Reward" },
  { word: "Bunker", hint: "Protection" },
  { word: "Warehouse", hint: "Supply" },
  { word: "Museum", hint: "History" },
  { word: "Library", hint: "Knowledge" },
  { word: "Stadium", hint: "Crowd" },
  { word: "Hotel", hint: "Stay" },
  { word: "Airport", hint: "Departure" },
  { word: "Bridge", hint: "Connection" },
  { word: "Tunnel", hint: "Passage" },
  { word: "Factory", hint: "Industry" },
  { word: "Laboratory", hint: "Research" },
  { word: "Experiment", hint: "Testing" },
  { word: "Virus", hint: "Infection" },
  { word: "Doctor", hint: "Care" },
  { word: "Nurse", hint: "Support" },
  { word: "Soldier", hint: "Combat" },
  { word: "Tank", hint: "Force" },
  { word: "Grenade", hint: "Destruction" },
  { word: "Parachute", hint: "Descent" },
  { word: "Canyon", hint: "Depth" },
  { word: "Avalanche", hint: "Collapse" },
  { word: "Chainsaw", hint: "Cutting" },
  { word: "Wrench", hint: "Repair" },
  { word: "Hammer", hint: "Building" },
  { word: "Coffin", hint: "Death" },
  { word: "Ghost", hint: "Haunting" },
  { word: "Werewolf", hint: "Transformation" },
  { word: "Apple", hint: "Orchard" },
  { word: "Banana", hint: "Tropical" },
  { word: "Pizza", hint: "Casual" },
  { word: "Burger", hint: "Grill" },
  { word: "Taco", hint: "Folded" },
  { word: "Sushi", hint: "Precision" },
  { word: "Bacon", hint: "Sizzle" },
  { word: "Pancake", hint: "Morning" },
  { word: "Coffee", hint: "Energy" },
  { word: "Donut", hint: "Sweet" },
  { word: "Milkshake", hint: "Creamy" },
  { word: "Popcorn", hint: "Crunch" },
  { word: "Steak", hint: "Grill" },
  { word: "Spaghetti", hint: "Messy" },
  { word: "Ice Cream", hint: "Cold" },
  { word: "Refrigerator", hint: "Preservation" },
  { word: "Microwave", hint: "Convenience" },
  { word: "Toaster", hint: "Crisp" },
  { word: "Dishwasher", hint: "Cleaning" },
  { word: "Television", hint: "Viewing" },
  { word: "Remote", hint: "Control" },
  { word: "Laptop", hint: "Portable" },
  { word: "Keyboard", hint: "Input" },
  { word: "Mouse", hint: "Control" },
  { word: "iPhone", hint: "Device" },
  { word: "Android", hint: "Device" },
  { word: "Xbox", hint: "Console" },
  { word: "PlayStation", hint: "Console" },
  { word: "Nintendo", hint: "Console" },
  { word: "Headphones", hint: "Private" },
  { word: "Speaker", hint: "Volume" },
  { word: "Camera", hint: "Memory" },
  { word: "Drone", hint: "Remote" },
  { word: "Flashlight", hint: "Visibility" },
  { word: "Battery", hint: "Energy" },
  { word: "WiFi", hint: "Connection" },
  { word: "Password", hint: "Access" },
  { word: "Wallet", hint: "Carry" },
  { word: "Credit Card", hint: "Payment" },
  { word: "Lottery", hint: "Chance" },
  { word: "Bitcoin", hint: "Digital" },
  { word: "Stock Market", hint: "Speculation" },
  { word: "ATM", hint: "Withdrawal" },
  { word: "Gas Station", hint: "Refill" },
  { word: "Road Trip", hint: "Journey" },
  { word: "Cruise Ship", hint: "Leisure" },
  { word: "Passport", hint: "Access" },
  { word: "Suitcase", hint: "Packing" },
  { word: "Vacation", hint: "Escape" },
  { word: "Beach", hint: "Relaxation" },
  { word: "Surfboard", hint: "Balance" },
  { word: "Lobster", hint: "Luxury" },
  { word: "Octopus", hint: "Deep" },
  { word: "Dolphin", hint: "Intelligence" },
  { word: "Whale", hint: "Massive" },
  { word: "Penguin", hint: "Cold" },
  { word: "Eagle", hint: "Freedom" },
  { word: "Lion", hint: "Pride" },
  { word: "Tiger", hint: "Stripes" },
  { word: "Bear", hint: "Strength" },
  { word: "Wolf", hint: "Pack" },
  { word: "Snake", hint: "Danger" },
  { word: "Horse", hint: "Riding" },
  { word: "Cow", hint: "Pasture" },
  { word: "Chicken", hint: "Coop" },
  { word: "Pig", hint: "Mud" },
  { word: "Goat", hint: "Climbing" },
  { word: "Barn", hint: "Rural" },
  { word: "Tractor", hint: "Work" },
  { word: "Farmer", hint: "Harvest" },
  { word: "Scarecrow", hint: "Field" },
  { word: "Fishing Rod", hint: "Patience" },
  { word: "Bait", hint: "Lure" },
  { word: "Campfire", hint: "Warmth" },
  { word: "Tent", hint: "Shelter" },
  { word: "Sleeping Bag", hint: "Camping" },
  { word: "Sleeping Bag", hint: "Comfort" },
  { word: "Cabin", hint: "Retreat" },
  { word: "Mountain", hint: "Elevation" },
  { word: "Waterfall", hint: "Flow" },
  { word: "River", hint: "Current" },
  { word: "Lake", hint: "Stillness" },
  { word: "Forest", hint: "Wilderness" },
  { word: "Treehouse", hint: "Childhood" },
  { word: "Cave", hint: "Hidden" },
  { word: "Island", hint: "Isolation" },
  { word: "Glacier", hint: "Frozen" },
  { word: "Rainbow", hint: "Spectrum" },
  { word: "Thunder", hint: "Noise" },
  { word: "Lightning", hint: "Energy" },
  { word: "Cloud", hint: "Atmosphere" },
  { word: "Moon", hint: "Orbit" },
  { word: "Sun", hint: "Energy" },
  { word: "Planet", hint: "Orbit" },
  { word: "Alien", hint: "Unknown" },
  { word: "Black Hole", hint: "Gravity" },
  { word: "Meteor", hint: "Impact" },
  { word: "UFO", hint: "Mystery" },
  { word: "Wizard", hint: "Knowledge" },
  { word: "Knight", hint: "Honor" },
  { word: "King", hint: "Leadership" },
  { word: "Queen", hint: "Leadership" },
  { word: "Prince", hint: "Inheritance" },
  { word: "Princess", hint: "Inheritance" },
  { word: "Treasure Map", hint: "Discovery" },
  { word: "Magic Wand", hint: "Power" },
  { word: "Potion", hint: "Transformation" },
  { word: "Unicorn", hint: "Rarity" },
  { word: "Fairy", hint: "Wonder" },
  { word: "Goblin", hint: "Mischief" },
  { word: "Dungeon", hint: "Captivity" },
  { word: "Superhero", hint: "Responsibility" },
  { word: "Villain", hint: "Conflict" },
  { word: "Secret Agent", hint: "Espionage" },
  { word: "Spy", hint: "Deception" },
  { word: "Bodyguard", hint: "Protection" },
  { word: "Bounty Hunter", hint: "Pursuit" },
  { word: "Race Car", hint: "Racing" },
  { word: "Race Car", hint: "Speed" },
  { word: "Monster Truck", hint: "Power" },
  { word: "Bulldozer", hint: "Force" },
  { word: "Excavator", hint: "Digging" },
  { word: "Traffic Light", hint: "Control" },
  { word: "Parking Lot", hint: "Waiting" },
  { word: "Movie Theater", hint: "Audience" },
  { word: "Concert", hint: "Performance" },
  { word: "Microphone", hint: "Amplification" },
  { word: "Guitar", hint: "Strings" },
  { word: "Piano", hint: "Keys" },
  { word: "Drums", hint: "Rhythm" },
  { word: "Violin", hint: "Strings" },
  { word: "Trumpet", hint: "Brass" },
  { word: "DJ", hint: "Mixing" },
  { word: "Singer", hint: "Vocals" },
  { word: "Actor", hint: "Portrayal" },
  { word: "Director", hint: "Vision" },
  { word: "Oscar", hint: "Recognition" },
  { word: "Olympics", hint: "Competition" },
  { word: "Football", hint: "Teamwork" },
  { word: "Basketball", hint: "Teamwork" },
  { word: "Baseball", hint: "Timing" },
  { word: "Soccer", hint: "Teamwork" },
  { word: "Golf", hint: "Precision" },
  { word: "Tennis", hint: "Reaction" },
  { word: "Bowling", hint: "Accuracy" },
  { word: "Boxing", hint: "Endurance" },
  { word: "Wrestling", hint: "Grappling" },
  { word: "Referee", hint: "Rules" },
  { word: "Trophy", hint: "Achievement" },
  { word: "Medal", hint: "Achievement" },
  { word: "Army", hint: "Service" },
  { word: "Navy", hint: "Service" },
  { word: "Air Force", hint: "Service" },
  { word: "Marine", hint: "Service" },
  { word: "Barracks", hint: "Housing" },
  { word: "Deployment", hint: "Assignment" },
  { word: "Parade", hint: "Display" },
  { word: "Wedding", hint: "Commitment" },
  { word: "Birthday", hint: "Milestone" },
  { word: "Christmas", hint: "Tradition" },
  { word: "Halloween", hint: "Costumes" },
  { word: "Thanksgiving", hint: "Gathering" },
  { word: "Fireworks", hint: "Celebration" },
  { word: "Barbecue", hint: "Gathering" },
  { word: "Food Truck", hint: "Convenience" },
  { word: "Chef", hint: "Creation" },
  { word: "Waiter", hint: "Service" },
  { word: "Judge", hint: "Decision" },
  { word: "Lawyer", hint: "Argument" },
  { word: "Handcuffs", hint: "Restraint" },
  { word: "Fingerprint", hint: "Identity" },
  { word: "Crime Scene", hint: "Evidence" },
  { word: "Evidence", hint: "Proof" },
  { word: "Safe", hint: "Protection" },
  { word: "Lock", hint: "Restriction" },
  { word: "Vault", hint: "Protection" },
  { word: "Blueprint", hint: "Planning" },
  { word: "Construction", hint: "Creation" },
  { word: "Elevator", hint: "Movement" },
  { word: "Escalator", hint: "Movement" },
  { word: "Shopping Mall", hint: "Commerce" },
  { word: "Supermarket", hint: "Necessities" },
  { word: "Vending Machine", hint: "Convenience" },
  { word: "Arcade", hint: "Competition" },
  { word: "Board Game", hint: "Strategy" },
  { word: "Puzzle", hint: "Problem Solving" },
  { word: "Dice", hint: "Chance" },
  { word: "Chess", hint: "Strategy" },
  { word: "Playing Cards", hint: "Chance" },
];

export default wordPairs;