const wordPairs = [
      { word: "Firetruck", hint: "Emergency Vehicle" },
  { word: "Casino", hint: "Gambling" },
  { word: "Tattoo", hint: "Ink" },
  { word: "Motorcycle", hint: "Vehicle" },
  { word: "Prison", hint: "Jail" },
  { word: "Volcano", hint: "Lava" },
  { word: "Astronaut", hint: "Space" },
  { word: "Submarine", hint: "Ocean" },
  { word: "Dragon", hint: "Fantasy" },
  { word: "Cemetery", hint: "Graveyard" },
  { word: "Helicopter", hint: "Aircraft" },
  { word: "Shotgun", hint: "Weapon" },
  { word: "Whiskey", hint: "Alcohol" },
  { word: "Skyscraper", hint: "Building" },
  { word: "Tornado", hint: "Storm" },
  { word: "Detective", hint: "Investigator" },
  { word: "Mansion", hint: "House" },
  { word: "Pirate", hint: "Sailor" },
  { word: "Bank", hint: "Money" },
  { word: "Diamond", hint: "Gem" },
  { word: "Robot", hint: "Machine" },
  { word: "Ambulance", hint: "Emergency" },
  { word: "Nightclub", hint: "Dancing" },
  { word: "Sword", hint: "Weapon" },
  { word: "Hospital", hint: "Medical" },
  { word: "Airplane", hint: "Flight" },
  { word: "Train", hint: "Railroad" },
  { word: "Shark", hint: "Ocean" },
  { word: "Lighthouse", hint: "Beacon" },
  { word: "Castle", hint: "Kingdom" },
  { word: "Zombie", hint: "Monster" },
  { word: "Vampire", hint: "Monster" },
  { word: "Police", hint: "Law" },
  { word: "Courtroom", hint: "Trial" },
  { word: "Bullet", hint: "Ammunition" },
  { word: "Rocket", hint: "Space" },
  { word: "Satellite", hint: "Orbit" },
  { word: "Backpack", hint: "Bag" },
  { word: "Cigar", hint: "Smoke" },
  { word: "Gold", hint: "Treasure" },
  { word: "Crown", hint: "Royalty" },
  { word: "Throne", hint: "Royalty" },
  { word: "Jungle", hint: "Forest" },
  { word: "Desert", hint: "Sand" },
  { word: "Blizzard", hint: "Snow" },
  { word: "Hurricane", hint: "Storm" },
  { word: "Compass", hint: "Direction" },
  { word: "Treasure", hint: "Gold" },
  { word: "Bunker", hint: "Shelter" },
  { word: "Warehouse", hint: "Storage" },
  { word: "Museum", hint: "Exhibits" },
  { word: "Library", hint: "Books" },
  { word: "Stadium", hint: "Sports" },
  { word: "Hotel", hint: "Travel" },
  { word: "Airport", hint: "Travel" },
  { word: "Bridge", hint: "Crossing" },
  { word: "Tunnel", hint: "Underground" },
  { word: "Factory", hint: "Production" },
  { word: "Laboratory", hint: "Science" },
  { word: "Experiment", hint: "Science" },
  { word: "Virus", hint: "Disease" },
  { word: "Doctor", hint: "Medical" },
  { word: "Nurse", hint: "Medical" },
  { word: "Soldier", hint: "Military" },
  { word: "Tank", hint: "Military" },
  { word: "Grenade", hint: "Explosive" },
  { word: "Parachute", hint: "Skydiving" },
  { word: "Canyon", hint: "Cliff" },
  { word: "Avalanche", hint: "Snow" },
  { word: "Chainsaw", hint: "Tool" },
  { word: "Wrench", hint: "Tool" },
  { word: "Hammer", hint: "Tool" },
  { word: "Coffin", hint: "Funeral" },
  { word: "Ghost", hint: "Spirit" },
  { word: "Werewolf", hint: "Monster" },
    { word: "Apple", hint: "Fruit" },
  { word: "Banana", hint: "Fruit" },
  { word: "Pizza", hint: "Food" },
  { word: "Burger", hint: "Food" },
  { word: "Taco", hint: "Food" },
  { word: "Sushi", hint: "Food" },
  { word: "Bacon", hint: "Breakfast" },
  { word: "Pancake", hint: "Breakfast" },
  { word: "Coffee", hint: "Drink" },
  { word: "Donut", hint: "Dessert" },
  { word: "Milkshake", hint: "Dessert" },
  { word: "Popcorn", hint: "Snack" },
  { word: "Steak", hint: "Dinner" },
  { word: "Spaghetti", hint: "Pasta" },
  { word: "Ice Cream", hint: "Dessert" },
  { word: "Refrigerator", hint: "Kitchen" },
  { word: "Microwave", hint: "Kitchen" },
  { word: "Toaster", hint: "Kitchen" },
  { word: "Dishwasher", hint: "Kitchen" },
  { word: "Television", hint: "Entertainment" },
  { word: "Remote", hint: "Electronics" },
  { word: "Laptop", hint: "Computer" },
  { word: "Keyboard", hint: "Computer" },
  { word: "Mouse", hint: "Computer" },
  { word: "iPhone", hint: "Smartphone" },
  { word: "Android", hint: "Smartphone" },
  { word: "Xbox", hint: "Gaming" },
  { word: "PlayStation", hint: "Gaming" },
  { word: "Nintendo", hint: "Gaming" },
  { word: "Headphones", hint: "Audio" },
  { word: "Speaker", hint: "Audio" },
  { word: "Camera", hint: "Photography" },
  { word: "Drone", hint: "Flying" },
  { word: "Flashlight", hint: "Light" },
  { word: "Battery", hint: "Power" },
  { word: "WiFi", hint: "Internet" },
  { word: "Password", hint: "Security" },
  { word: "Wallet", hint: "Money" },
  { word: "Credit Card", hint: "Money" },
  { word: "Lottery", hint: "Luck" },
  { word: "Bitcoin", hint: "Cryptocurrency" },
  { word: "Stock Market", hint: "Investing" },
  { word: "ATM", hint: "Banking" },
  { word: "Gas Station", hint: "Fuel" },
  { word: "Road Trip", hint: "Travel" },
  { word: "Cruise Ship", hint: "Travel" },
  { word: "Passport", hint: "Travel" },
  { word: "Suitcase", hint: "Travel" },
  { word: "Vacation", hint: "Travel" },
  { word: "Beach", hint: "Ocean" },
  { word: "Surfboard", hint: "Ocean" },
  { word: "Lobster", hint: "Seafood" },
  { word: "Octopus", hint: "Ocean Animal" },
  { word: "Dolphin", hint: "Ocean Animal" },
  { word: "Whale", hint: "Ocean Animal" },
  { word: "Penguin", hint: "Bird" },
  { word: "Eagle", hint: "Bird" },
  { word: "Lion", hint: "Animal" },
  { word: "Tiger", hint: "Animal" },
  { word: "Bear", hint: "Animal" },
  { word: "Wolf", hint: "Animal" },
  { word: "Snake", hint: "Animal" },
  { word: "Horse", hint: "Animal" },
  { word: "Cow", hint: "Farm" },
  { word: "Chicken", hint: "Farm" },
  { word: "Pig", hint: "Farm" },
  { word: "Goat", hint: "Farm" },
  { word: "Barn", hint: "Farm" },
  { word: "Tractor", hint: "Farm" },
  { word: "Farmer", hint: "Agriculture" },
  { word: "Scarecrow", hint: "Farm" },
  { word: "Fishing Rod", hint: "Fishing" },
  { word: "Bait", hint: "Fishing" },
  { word: "Campfire", hint: "Camping" },
  { word: "Tent", hint: "Camping" },  { word: "Sleeping Bag", hint: "Camping" },
  { word: "Cabin", hint: "Wilderness" },
  { word: "Mountain", hint: "Nature" },
  { word: "Waterfall", hint: "Nature" },
  { word: "River", hint: "Nature" },
  { word: "Lake", hint: "Nature" },
  { word: "Forest", hint: "Nature" },
  { word: "Treehouse", hint: "Tree" },
  { word: "Cave", hint: "Underground" },
  { word: "Island", hint: "Ocean" },
  { word: "Glacier", hint: "Ice" },
  { word: "Rainbow", hint: "Weather" },
  { word: "Thunder", hint: "Storm" },
  { word: "Lightning", hint: "Storm" },
  { word: "Cloud", hint: "Sky" },
  { word: "Moon", hint: "Space" },
  { word: "Sun", hint: "Space" },
  { word: "Planet", hint: "Space" },
  { word: "Alien", hint: "Space" },
  { word: "Black Hole", hint: "Space" },
  { word: "Meteor", hint: "Space" },
  { word: "UFO", hint: "Space" },
  { word: "Wizard", hint: "Magic" },
  { word: "Knight", hint: "Medieval" },
  { word: "King", hint: "Royalty" },
  { word: "Queen", hint: "Royalty" },
  { word: "Prince", hint: "Royalty" },
  { word: "Princess", hint: "Royalty" },
  { word: "Treasure Map", hint: "Pirate" },
  { word: "Magic Wand", hint: "Magic" },
  { word: "Potion", hint: "Magic" },
  { word: "Unicorn", hint: "Fantasy" },
  { word: "Fairy", hint: "Fantasy" },
  { word: "Goblin", hint: "Fantasy" },
  { word: "Dungeon", hint: "Fantasy" },
  { word: "Superhero", hint: "Comic" },
  { word: "Villain", hint: "Comic" },
  { word: "Secret Agent", hint: "Spy" },
  { word: "Spy", hint: "Secrets" },
  { word: "Bodyguard", hint: "Protection" },
  { word: "Bounty Hunter", hint: "Tracking" },
  { word: "Race Car", hint: "Racing" },
  { word: "Monster Truck", hint: "Vehicle" },
  { word: "Bulldozer", hint: "Construction" },
  { word: "Excavator", hint: "Construction" },
  { word: "Traffic Light", hint: "Road" },
  { word: "Parking Lot", hint: "Cars" },
  { word: "Movie Theater", hint: "Entertainment" },
  { word: "Concert", hint: "Music" },
  { word: "Microphone", hint: "Audio" },
  { word: "Guitar", hint: "Instrument" },
  { word: "Piano", hint: "Instrument" },
  { word: "Drums", hint: "Instrument" },
  { word: "Violin", hint: "Instrument" },
  { word: "Trumpet", hint: "Instrument" },
  { word: "DJ", hint: "Music" },
  { word: "Singer", hint: "Music" },
  { word: "Actor", hint: "Movies" },
  { word: "Director", hint: "Movies" },
  { word: "Oscar", hint: "Award" },
  { word: "Olympics", hint: "Sports" },
  { word: "Football", hint: "Sport" },
  { word: "Basketball", hint: "Sport" },
  { word: "Baseball", hint: "Sport" },
  { word: "Soccer", hint: "Sport" },
  { word: "Golf", hint: "Sport" },
  { word: "Tennis", hint: "Sport" },
  { word: "Bowling", hint: "Sport" },
  { word: "Boxing", hint: "Sport" },
  { word: "Wrestling", hint: "Sport" },
  { word: "Referee", hint: "Sports" },
  { word: "Trophy", hint: "Winner" },
  { word: "Medal", hint: "Winner" },
  { word: "Army", hint: "Military" },
  { word: "Navy", hint: "Military" },
  { word: "Air Force", hint: "Military" },
  { word: "Marine", hint: "Military" },
  { word: "Barracks", hint: "Military" },
  { word: "Deployment", hint: "Military" },
  { word: "Parade", hint: "Celebration" },
  { word: "Wedding", hint: "Marriage" },
  { word: "Birthday", hint: "Celebration" },
  { word: "Christmas", hint: "Holiday" },
  { word: "Halloween", hint: "Holiday" },
  { word: "Thanksgiving", hint: "Holiday" },
  { word: "Fireworks", hint: "Celebration" },
  { word: "Barbecue", hint: "Cooking" },
  { word: "Food Truck", hint: "Restaurant" },
  { word: "Chef", hint: "Cooking" },
  { word: "Waiter", hint: "Restaurant" },
  { word: "Judge", hint: "Court" },
  { word: "Lawyer", hint: "Court" },
  { word: "Handcuffs", hint: "Police" },
  { word: "Fingerprint", hint: "Evidence" },
  { word: "Crime Scene", hint: "Investigation" },
  { word: "Evidence", hint: "Investigation" },
  { word: "Safe", hint: "Security" },
  { word: "Lock", hint: "Security" },
  { word: "Vault", hint: "Security" },
  { word: "Blueprint", hint: "Design" },
  { word: "Construction", hint: "Building" },
  { word: "Elevator", hint: "Building" },
  { word: "Escalator", hint: "Building" },
  { word: "Shopping Mall", hint: "Stores" },
  { word: "Supermarket", hint: "Groceries" },
  { word: "Vending Machine", hint: "Snack" },
  { word: "Arcade", hint: "Gaming" },
  { word: "Board Game", hint: "Gaming" },
  { word: "Puzzle", hint: "Game" },
  { word: "Dice", hint: "Game" },
  { word: "Chess", hint: "Strategy" },
  { word: "Playing Cards", hint: "Game" },
];

export default wordPairs;